# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: distribution/dnsconfd.spec

# add or remove files that should be synced
files_to_sync:
    - distribution/dnsconfd.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: dnsconfd
# downstream (Fedora) RPM package name
downstream_package_name: dnsconfd

update_release: false
actions:
    get-current-version: "sed -n 's|^Version: *||p' distribution/dnsconfd.spec"

jobs:
  - job: copr_build
    trigger: pull_request
    identifier: pr_copr_build
    targets:
      - fedora-all
  - job: tests
    trigger: pull_request
    identifier: pr_tests
    targets:
    - fedora-40
  - job: copr_build
    trigger: commit
    identifier: commit_copr_build
    targets:
      - fedora-all
  - job: tests
    trigger: commit
    identifier: commit_tests
    targets:
      - fedora-40
