# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: distribution/dnsconfd.spec

# add or remove files that should be synced
files_to_sync:
    - distribution/dnsconfd.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: dnsconfd
# downstream (Fedora) RPM package name
downstream_package_name: dnsconfd

update_release: false
actions:
    get-current-version: "sed -n 's|^Version: *||p' distribution/dnsconfd.spec"

jobs:
# pr jobs
  - job: copr_build
    trigger: pull_request
    identifier: pr_copr_build
    targets:
      - fedora-42
      - fedora-rawhide
      - centos-stream-10
      - centos-stream-9
  - job: tests
    trigger: pull_request
    identifier: pr_tests_multihost
    targets:
      - fedora-42
      - fedora-rawhide
      - centos-stream-10
      - centos-stream-9
    tmt_plan: multihost
    skip_build: True
    tf_extra_params:
      settings:
        pipeline:
          type: tmt-multihost
    use_internal_tf: True
  - job: tests
    trigger: pull_request
    identifier: pr_tests_singlehost
    targets:
      - fedora-42
      - fedora-rawhide
      - centos-stream-10
      - centos-stream-9
    tmt_plan: "(integration|distribution|unit)"
    skip_build: True
# commit jobs (executed on main branch)
  - job: copr_build
    trigger: commit
    identifier: commit_copr_build
    targets:
      - fedora-42
      - fedora-rawhide
      - centos-stream-10
      - centos-stream-9
  - job: tests
    trigger: commit
    identifier: pr_tests_multihost
    targets:
      - fedora-42
      - fedora-rawhide
      - centos-stream-10
      - centos-stream-9
    tmt_plan: multihost
    skip_build: True
    tf_extra_params:
      settings:
        pipeline:
          type: tmt-multihost
    use_internal_tf: True
  - job: tests
    trigger: commit
    identifier: pr_tests_singlehost
    targets:
      - fedora-42
      - fedora-rawhide
      - centos-stream-10
      - centos-stream-9
    tmt_plan: "(integration|distribution|unit)"
    skip_build: True
