# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: distribution/dnsconfd.spec

# add or remove files that should be synced
files_to_sync:
    - distribution/dnsconfd.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: dnsconfd
# downstream (Fedora) RPM package name
downstream_package_name: dnsconfd

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
  - job: tests
    trigger: pull_request
    targets:
    - fedora-39
