[Service]
ExecStartPost=+/bin/sh -c 'echo ready > /run/dnsconfd/unbound_status;'
ExecStopPost=+/bin/sh -c 'if [ "$SERVICE_RESULT" != "success" ]; then echo fail > /run/dnsconfd/unbound_status; else echo stopped > /run/dnsconfd/unbound_status; fi'
