.TH "dnsconfd.conf" "5" "10 Oct 2023" "dnsconfd-1.4.1" ""

.SH NAME

dnsconfd.conf - dnsconfd configuration file

.SH DESCRIPTION

Dnsconfd.conf is YAML formatted configuration file altering behaviour of Dnsconfd.

.SH OPTIONS

.IP "dbus_name"
DBUS name that dnsconfd should use, default org.freedesktop.resolve1
.IP "log_level"
Log level of dnsconfd, default INFO
.IP "resolv_conf_path"
Path to resolv.conf that the dnsconfd should manage, default /etc/resolv.conf
.IP "prioritize_wire"
If set to yes then wireless interfaces will have lower priority, default yes
.IP "listen_address"
Address on which local resolver listens, default 127.0.0.1
.IP "resolver_options"
Options to be used in resolv.conf for alteration of resolver, default "edns0 trust-ad"
.IP "dnssec_enabled"
Enable dnssec record validation, default no
.IP "handle_routing"
Dnsconfd will submit necessary routes to routing manager, default yes
.IP "static_servers"
List of servers that should be configured, default is empty
.IP "api_choice"
Dnsconfd will switch between APIs. Allowed options are resolve1 and dnsconfd.
Default is resolve1

Available attributes of servers are:

 \(bu \fBaddress\fP required, string of servers ip address
 \(bu \fBprotocol\fP optional, DoT or plain
 \(bu \fBsni\fP optional, server name indication used for TLS checks
 \(bu \fBport\fP optional, port on which server is listening. If not given then 53 is used for plain protocol and 853 for DoT

Examples:

Enabling one global server using DNS over TLS

static_servers:
   - address: 192.168.6.3
     protocol: "DoT"
     sni: named

Enabling one server for specific domain and second for everything else

static_servers:
    - address: 192.168.6.3
    - address: 192.168.6.4
      domains:
        - domain: domain.com
          search: true

.IP "ignore_api"
If enabled, dnsconfd will ignore configuration received through API, default no

.SH "REPORTING BUGS"
Please for reporting bugs use Github repository https://github.com/InfrastructureServices/dnsconfd

.SH "SEE ALSO"
\fB dnsconfd(8)\fP Dnsconfd daemon
\fB dnsconfd-status(8)\fP Checking status of dnsconfd
\fB dnsconfd-reload(8)\fP Reload running cache service
\fB dnsconfd-config(8)\fP Change configuration of host
\fB dnsconfd-update(8)\fP Change Dnsconfd configuration

.SH COPYRIGHT

Copyright (c) 2023 Red Hat, Inc.