.TH "dnsconfd-status" "8" "10 Oct 2023" "dnsconfd-1.5.0" ""

.SH NAME

dnsconfd-update - Change Dnsconfd configuration

.SH SYNOPSIS

dnsconfd update <server_list> <mode>

.SH DESCRIPTION

Update command changes dnsconfd configuration of forwarders.

.SH OPTIONS

.IP "server_list"
JSON formatted List of forwarders that should be used by dnsconfd and
underlying cache service.
.IP "mode"
Integer representing resolving mode Dnsconfd should work in.
Valid values are:
 \(bu \fB0\fP - Free, all available server can be used for resolving of all names
 \(bu \fB1\fP - Global restrictive, only global servers (not bound to interface) can be used for resolving of all names. Bound servers can resolve only subdomains
 \(bu \fB2\fP - Full restrictive, only global servers will be used for resolving

Available fields of servers are:

 \(bu \fBaddress\fP required, string of servers ip address
 \(bu \fBprotocol\fP optional, DoT or plain
 \(bu \fBname\fP optional, name that should be present in server's TLS certificate
 \(bu \fBport\fP optional, port on which server is listening. If not given then 53 is used for plain protocol and 853 for DoT
 \(bu \fBrouting_domains\fP optional, list of strings with the domain name whose members will be resolved only by this or other servers with the same domain entry
 \(bu \fBsearch_domains\fP optional, list of strings with the domains that should be used for host-name lookup
 \(bu \fBinterface\fP optional, integer indicating if server can be used only through interface with this interface index.
 \(bu \fBdnssec\fP optional, boolean indicating whether this server supports dnssec or not
 \(bu \fBnetworks\fP optional, list of strings representing networks whose reverse dns records must be resolved by this server
 \(bu \fBfirewall_zone\fP optional, string indicating name of firewall zone that this server should be associated with

.IP "-h, --help"
Show help message and exit

.SH "EXIT STATUS"

.IP 0
Everything went as expected.
.IP 1
Error occurred.
.IP 13
Bad arguments.

.SH EXAMPLES
# dnsconfd update '[{"address":"192.168.6.3", "interface": 3}]' 0

Use only one server for all queries and only through interface with index 3.

# dnsconfd update '[{"address":"192.168.6.3", "protocol": "DoT", "name": "named"}]' 0

Use only one server for all queries, enable dns over tls and verify that server
presents certificate containing hostname 'named'.

# dnsconfd update '[{"address":"192.168.6.3", "routing_domains": ["example.com"], "interface": 3}, {"address":"2001:db8::103"}]' 0

Use server 192.168.6.3 for resolving names under domain example.com, but do not use the domain for
host-name lookup and use 2001:db8::103 for resolving of any other name.

This would have the same effect with Global restrictive mode, but with full restrictive mode,
even names belonging to example.com would be resolved through 2001:db8::103. To achieve the
same effect with all modes, server 192.168.6.3 must not be bound to any interface (be global).

.SH "LIMITATIONS"
This command only supports dnsconfd API. See api_choice option for further information.

.SH "REPORTING BUGS"
Please for reporting bugs use Github repository https://github.com/InfrastructureServices/dnsconfd

.SH "SEE ALSO"
\fB dnsconfd(8)\fP Dnsconfd daemon
\fB dnsconfd-reload(8)\fP Reload running cache service
\fB dnsconfd-config(8)\fP Change configuration of underlying service or host
\fB dnsconfd-status(8)\fP Check status of dnsconfd
\fB dnsconfd.conf(5)\fP Dnsconfd configuration file

.SH COPYRIGHT

Copyright (c) 2023 Red Hat, Inc.