.TH "dnsconfd.conf" "5" "07 Jan 2026" "dnsconfd-1.7.5" ""

.SH NAME

dnsconfd.conf - dnsconfd configuration file

.SH DESCRIPTION

Dnsconfd.conf is YAML formatted configuration file altering behaviour of Dnsconfd.

.SH OPTIONS

.IP "dbus_name"
DBUS name that dnsconfd should use, default com.redhat.dnsconfd
.IP "log_level"
Log level of dnsconfd, default INFO
.IP "resolv_conf_path"
Path to resolv.conf that the dnsconfd should manage, default /etc/resolv.conf
.IP "prioritize_wire"
If set to yes then wireless interfaces will have lower priority, default yes
.IP "listen_address"
Address on which local resolver listens, default 127.0.0.1
.IP "resolver_options"
Options to be used in resolv.conf for alteration of resolver, default "edns0 trust-ad"
.IP "dnssec_enabled"
Enable dnssec record validation, default no
.IP "handle_routing"
Dnsconfd will submit necessary routes to routing manager, default yes
.IP "api_choice"
Dnsconfd will switch between APIs. Allowed options are resolve1 and dnsconfd.
Default is dnsconfd
.IP stderr_log
Dnsconfd will write logs into stderr, default yes
.IP journal_log
Dnsconfd will send logs into journal, default no
.IP syslog_log
Dnsconfd will send logs into syslog destination specified by this option,
by default disabled. See command line option for destination specification
syntax.
.IP file_log
Dnsconfd will write logs into specified file, not used by default
.IP certification_authority
Absolute path to a bundle of certification authorities that will be used
when no custom were specified.
.IP "static_servers"
List of servers that should be configured, default is empty
.IP "certification_authority"
Space separated list of CA bundles used for encrypted protocols as default
when no custom CA was specified. The first one that can be accessed will be
used, default /etc/pki/dns/extracted/pem/tls-ca-bundle.pem /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

Available attributes of servers are:

 \(bu \fBaddress\fP required, string of servers ip address
 \(bu \fBprotocol\fP optional, DoT or plain
 \(bu \fBname\fP optional, name that should be present in server's TLS certificate
 \(bu \fBport\fP optional, port on which server is listening. If not given then 53 is used for plain protocol and 853 for DoT
 \(bu \fBrouting_domains\fP optional, domains whose resolution should be performed through this server
 \(bu \fBsearch_domains\fP optional, domains that should be used for host-name lookup
 \(bu \fBdnssec\fP optional, boolean indicating whether this server supports dnssec or not
 \(bu \fBnetworks\fP optional, networks whose reverse dns records must be resolved by this server

Examples:

Enabling one global server using DNS over TLS

static_servers:
   - address: 192.168.6.3
     protocol: "dns+tls"
     name: named

Enabling one server for specific domain and second for everything else

static_servers:
    - address: 192.168.6.3
    - address: 192.168.6.4
      routing_domains:
        - example.com

.IP "ignore_api"
If enabled, dnsconfd will ignore configuration received through API, default no

.SH "REPORTING BUGS"
Please for reporting bugs use Github repository https://github.com/InfrastructureServices/dnsconfd

.SH "SEE ALSO"
\fB dnsconfd(8)\fP Dnsconfd daemon
\fB dnsconfd-status(8)\fP Checking status of dnsconfd
\fB dnsconfd-reload(8)\fP Reload running cache service
\fB dnsconfd-config(8)\fP Change configuration of host
\fB dnsconfd-update(8)\fP Change Dnsconfd configuration

.SH COPYRIGHT

Copyright (c) 2023 Red Hat, Inc.
