.TH "dnsconfd" "8" "10 Oct 2023" "dnsconfd-0.0.3" ""

.SH NAME

Dnsconfd - local DNS cache configuration daemon

.SH SYNOPSIS

dnsconfd [options]

.SH DESCRIPTION

Dnsconfd is a local cache configuration daemon. It implements DBus interface of systemd-resolved
and translates it's use to dns service's configuration.

.SH OPTIONS

.IP "-h, --help"
Show help message and exit
.IP "--dbus-name DBUS_NAME"
DBUS name that dnsconfd should use, default com.redhat.dnsconfd
.IP "--log-level {DEBUG,INFO,WARN}"
Log level of dnsconfd, default INFO
.IP "--resolv-conf-path RESOLV_CONF_PATH"
Path to resolv.conf that the dnsconfd should manage, default /etc/resolv.conf
.IP "--prioritize-wire {yes,no}"
If set to yes then wireless interfaces will have lower priority, default yes
.IP "--listen-address ADDRESS"
Address on which local resolver listens, default 127.0.0.1
.IP "--config-file PATH"
Path where config file is located, default /etc/dnsconfd.conf

.SH "EXIT STATUS"

.IP 0
Graceful stop.
.IP 1
DNS caching service failure. Service crashed for example.
.IP 2
Failed communication through DBUS.
.IP 3
Failed interaction with resolv.conf

.SH ENVIRONMENT
Environment variables have lower priority than command line options but higher
than configuration file.

.IP DBUS_NAME
DBUS name that dnsconfd should use, default com.redhat.dnsconfd
.IP LOG_LEVEL
Log level of dnsconfd, default INFO
.IP RESOLV_CONF_PATH
Path to resolv.conf that the dnsconfd should manage, default /etc/resolv.conf
.IP PRIORITIZE_WIRE
If set to yes then wireless interfaces will have lower priority, default yes
.IP LISTEN_ADDRESS
Address on which local resolver listens, default 127.0.0.1
.IP CONFIG_FILE
Path where config file is located, default /etc/dnsconfd.conf

.SH FILES
Dnsconfd manages resolv.conf to route domain name resolution to local cache service.
Default location of the configuration file is /etc/dnsconfd.conf.

.SH NOTES
The only currently supported backend is Unbound.

.SH "REPORTING BUGS"
Please for reporting bugs use Github repository https://github.com/InfrastructureServices/dnsconfd

.SH "SEE ALSO"
\fB dnsconfd-status(8)\fP Checking status of dnsconfd
\fB dnsconfd-reload(8)\fP Reload running cache service
\fB dnsconfd-config(8)\fP Change configuration of service or host

.SH COPYRIGHT

Copyright (c) 2023 Red Hat, Inc.