.TH "dnsconfd-config" "8" "09 Apr 2025" "dnsconfd-1.7.3" ""

.SH NAME

dnsconfd-config - Change configuration of host

.SH SYNOPSIS

dnsconfd config <command> [options]

.SH DESCRIPTION

Config command allows you to change configuration of service or host.

.SH COMMANDS

.IP nm_enable
Config network manager to use dnsconfd
.IP nm_disable
Config network manager to not use dnsconfd
.IP take_resolvconf
Change ownership of resolv conf, so dnsconfd does not need root privileges
.IP return_resolvconf
Return ownership of resolv conf, so root is again the owner
.IP install
Perform all installation steps
.IP uninstall
Perform all uninstallation steps

.SH OPTIONS

.IP "-h, --help"
Show help message and exit

.SH "EXIT STATUS"

.IP 0
Everything went as expected.
.IP 1
Error occurred.
.IP 13
Bad arguments.

.SH ENVIRONMENT
Environment variables have lower priority than command line options but higher
than configuration file.

.IP DBUS_NAME
DBUS name that dnsconfd should use, default org.freedesktop.resolve1
.IP LOG_LEVEL
Log level of dnsconfd, default INFO
.IP CONFIG_FILE
Path where config file is located, default /etc/dnsconfd.conf

.SH "REPORTING BUGS"
Please for reporting bugs use Github repository https://github.com/InfrastructureServices/dnsconfd

.SH "SEE ALSO"
\fB dnsconfd(8)\fP Dnsconfd daemon
\fB dnsconfd-reload(8)\fP Reload running cache service
\fB dnsconfd-status(8)\fP Check status of dnsconfd
\fB dnsconfd-update(8)\fP Change Dnsconfd configuration
\fB dnsconfd.conf(5)\fP Dnsconfd configuration file

.SH COPYRIGHT

Copyright (c) 2023 Red Hat, Inc.