.TH "dnsconfd-status" "8" "19 Feb 2025" "dnsconfd-1.7.2" ""

.SH NAME

dnsconfd-status - Check status of dnsconfd

.SH SYNOPSIS

dnsconfd status [options]

.SH DESCRIPTION

Status command allows you to retrieve status of running dnsconfd instance.

.SH OPTIONS

.IP "-h, --help"
Show help message and exit
.IP "--json"
Status should be formatted as JSON string

.SH "EXIT STATUS"

.IP 0
Everything went as expected.
.IP 1
Error occurred.
.IP 13
Bad arguments.

.SH ENVIRONMENT
Environment variables have lower priority than command line options but higher
than configuration file.

.IP DBUS_NAME
DBUS name that dnsconfd should use, default com.redhat.dnsconfd
.IP LOG_LEVEL
Log level of dnsconfd, default INFO
.IP CONFIG_FILE
Path where config file is located, default /etc/dnsconfd.conf

.SH "REPORTING BUGS"
Please for reporting bugs use Github repository https://github.com/InfrastructureServices/dnsconfd

.SH "SEE ALSO"
\fB dnsconfd(8)\fP Dnsconfd daemon
\fB dnsconfd-reload(8)\fP Reload running cache service
\fB dnsconfd-config(8)\fP Change configuration of host
\fB dnsconfd-update(8)\fP Change Dnsconfd configuration
\fB dnsconfd.conf(5)\fP Dnsconfd configuration file

.SH COPYRIGHT

Copyright (c) 2023 Red Hat, Inc.