name: Nightly workflow
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
permissions:
  actions: none
  attestations: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger packit testing
        run: |
          jq -nc '{"body": "/packit build --commit main"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/InfrastructureServices/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
