name: Nightly workflow
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger packit testing
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/InfrastructureServices/dnsconfd/commits/$GITHUB_SHA/comments" \
            -d '{"body":"/packit build --commit main"}'
